package Solver;

import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.ComboBox;
import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;


public class Controller implements Initializable {
    public TextField tf_komCel;
    public TextField tf_mat_11;
    public TextField tf_mat_21;
    public TextField tf_mat_31;
    public TextField tf_mat_41;
    public TextField tf_mat_12;
    public TextField tf_mat_22;
    public TextField tf_mat_32;
    public TextField tf_mat_42;
    public TextField tf_mat_13;
    public TextField tf_mat_23;
    public TextField tf_mat_33;
    public TextField tf_mat_43;
    public TextField tf_mat_14;
    public TextField tf_mat_24;
    public TextField tf_mat_34;
    public TextField tf_mat_44;
    public TextField tf_mat_51;
    public TextField tf_mat_52;
    public TextField tf_mat_53;
    public TextField tf_mat_54;
    public TextField tf_mat_61;
    public TextField tf_mat_62;
    public TextField tf_mat_63;
    public TextField tf_mat_64;
    public TextField tf_zysk1;
    public TextField tf_zysk2;
    public TextField tf_zysk3;
    public TextField tf_zysk4;
    public ComboBox cb_IlMat;
    public Button button_licz;
    public TextField tf_ilSztuk1;
    public TextField tf_ilSztuk2;
    public TextField tf_ilSztuk3;
    public TextField tf_ilSztuk4;
    public TextField tf_warunek1;
    public TextField tf_warunek2;
    public TextField tf_warunek3;
    public TextField tf_warunek4;
    public TextField tf_warunek5;
    public TextField tf_warunek6;
    public ComboBox cb_ilWarunkow;

    private double _tf_mat_11;
    private double _tf_mat_21;
    private double _tf_mat_31;
    private double _tf_mat_41;
    private double _tf_mat_12;
    private double _tf_mat_22;
    private double _tf_mat_32;
    private double _tf_mat_42;
    private double _tf_mat_13;
    private double _tf_mat_23;
    private double _tf_mat_33;
    private double _tf_mat_43;
    private double _tf_mat_14;
    private double _tf_mat_24;
    private double _tf_mat_34;
    private double _tf_mat_44;
    private double _tf_mat_51;
    private double _tf_mat_52;
    private double _tf_mat_53;
    private double _tf_mat_54;
    private double _tf_mat_61;
    private double _tf_mat_62;
    private double _tf_mat_63;
    private double _tf_mat_64;
    private double _tf_warunek1;
    private double _tf_warunek2;
    private double _tf_warunek3;
    private double _tf_warunek4;
    private double _tf_warunek5;
    private double _tf_warunek6;

    private double _tf_zysk1;
    private double _tf_zysk2;
    private double _tf_zysk3;
    private double _tf_zysk4;

    private Integer illoscWarunkow;
    private Integer iloscMaterialu;

    private ObservableList<String> optionsIlWarunkow = FXCollections.observableArrayList("1", "2", "3", "4", "5", "6");
    private ObservableList<String> optionsIlMaterialu = FXCollections.observableArrayList("1", "2", "3", "4");

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        cb_ilWarunkow.setItems(optionsIlWarunkow);
        cb_IlMat.setItems(optionsIlMaterialu);

        cb_ilWarunkow.getSelectionModel().select(5);
        cb_IlMat.getSelectionModel().select(3);

        button_licz.setOnAction(event -> {
            _tf_mat_11 = Double.parseDouble(tf_mat_11.getText());
            _tf_mat_21 = Double.parseDouble(tf_mat_21.getText());
            _tf_mat_31 = Double.parseDouble(tf_mat_31.getText());
            _tf_mat_41 = Double.parseDouble(tf_mat_41.getText());
            _tf_mat_12 = Double.parseDouble(tf_mat_12.getText());
            _tf_mat_22 = Double.parseDouble(tf_mat_22.getText());
            _tf_mat_32 = Double.parseDouble(tf_mat_32.getText());
            _tf_mat_42 = Double.parseDouble(tf_mat_42.getText());
            _tf_mat_13 = Double.parseDouble(tf_mat_13.getText());
            _tf_mat_23 = Double.parseDouble(tf_mat_23.getText());
            _tf_mat_33 = Double.parseDouble(tf_mat_33.getText());
            _tf_mat_43 = Double.parseDouble(tf_mat_43.getText());
            _tf_mat_14 = Double.parseDouble(tf_mat_14.getText());
            _tf_mat_24 = Double.parseDouble(tf_mat_24.getText());
            _tf_mat_34 = Double.parseDouble(tf_mat_34.getText());
            _tf_mat_44 = Double.parseDouble(tf_mat_44.getText());
            _tf_mat_51 = Double.parseDouble(tf_mat_51.getText());
            _tf_mat_52 = Double.parseDouble(tf_mat_52.getText());
            _tf_mat_53 = Double.parseDouble(tf_mat_53.getText());
            _tf_mat_54 = Double.parseDouble(tf_mat_54.getText());
            _tf_mat_61 = Double.parseDouble(tf_mat_61.getText());
            _tf_mat_62 = Double.parseDouble(tf_mat_62.getText());
            _tf_mat_63 = Double.parseDouble(tf_mat_63.getText());
            _tf_mat_64 = Double.parseDouble(tf_mat_64.getText());
            _tf_zysk1 = Double.parseDouble(tf_zysk1.getText());
            _tf_zysk2 = Double.parseDouble(tf_zysk2.getText());
            _tf_zysk3 = Double.parseDouble(tf_zysk3.getText());
            _tf_zysk4 = Double.parseDouble(tf_zysk4.getText());
            _tf_warunek1 = Double.parseDouble(tf_warunek1.getText());
            _tf_warunek2 = Double.parseDouble(tf_warunek2.getText());
            _tf_warunek3 = Double.parseDouble(tf_warunek3.getText());
            _tf_warunek4 = Double.parseDouble(tf_warunek4.getText());
            _tf_warunek5 = Double.parseDouble(tf_warunek5.getText());
            _tf_warunek6 = Double.parseDouble(tf_warunek6.getText());

            System.out.println(illoscWarunkow + " " + iloscMaterialu);

            int n = illoscWarunkow; // number of decision variables (types of grain)
            int m = iloscMaterialu; // number of constraints (the ingredients)

            if (iloscMaterialu.equals(1)) {
                if (illoscWarunkow.equals(1)) {
                    double[][] A = {{_tf_mat_11}}; // Define the coefficient matrix for the constraint
                    double[] c = {_tf_zysk1}; // cost of each type of grain
                    double[] b = new double[]{_tf_warunek1}; // RHS of the constraints
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(2)) {
                    double[][] A = {{_tf_mat_11}, {_tf_mat_21}};
                    double[] c = {_tf_zysk1};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(3)) {
                    double[][] A = {{_tf_mat_11}, {_tf_mat_21}, {_tf_mat_31}};
                    double[] c = {_tf_zysk1};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(4)) {
                    double[][] A = {{_tf_mat_11}, {_tf_mat_21}, {_tf_mat_31}, {_tf_mat_41}};
                    double[] c = {_tf_zysk1};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(5)) {
                    double[][] A = {{_tf_mat_11}, {_tf_mat_21}, {_tf_mat_31}, {_tf_mat_41}, {_tf_mat_51}};
                    double[] c = {_tf_zysk1};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(6)) {
                    double[][] A = {{_tf_mat_11}, {_tf_mat_21}, {_tf_mat_31}, {_tf_mat_41}, {_tf_mat_51}, {_tf_mat_61}};
                    double[] c = {_tf_zysk1};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5, _tf_warunek6};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                }

            } else if (iloscMaterialu.equals(2)) {
                if (illoscWarunkow.equals(1)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12}};
                    double[] c = {_tf_zysk1, _tf_zysk2};
                    double[] b = new double[]{_tf_warunek1};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(2)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12}, {_tf_mat_21, _tf_mat_22}};
                    double[] c = {_tf_zysk1, _tf_zysk2};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(3)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12}, {_tf_mat_21, _tf_mat_22}, {_tf_mat_31, _tf_mat_32}};
                    double[] c = {_tf_zysk1, _tf_zysk2};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(4)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12}, {_tf_mat_21, _tf_mat_22}, {_tf_mat_31, _tf_mat_32}, {_tf_mat_41, _tf_mat_42}};
                    double[] c = {_tf_zysk1, _tf_zysk2};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(5)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12}, {_tf_mat_21, _tf_mat_22}, {_tf_mat_31, _tf_mat_32}, {_tf_mat_41, _tf_mat_42}
                            , {_tf_mat_51, _tf_mat_52}};
                    double[] c = {_tf_zysk1, _tf_zysk2};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(6)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12}, {_tf_mat_21, _tf_mat_22}, {_tf_mat_31, _tf_mat_32}, {_tf_mat_41, _tf_mat_42}
                            , {_tf_mat_51, _tf_mat_52}, {_tf_mat_61, _tf_mat_62}};
                    double[] c = {_tf_zysk1, _tf_zysk2};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5, _tf_warunek6};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                }

            } else if (iloscMaterialu.equals(3)) {
                if (illoscWarunkow.equals(1)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3};
                    double[] b = new double[]{_tf_warunek1};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(2)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13}, {_tf_mat_21, _tf_mat_22, _tf_mat_23}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(3)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13}, {_tf_mat_21, _tf_mat_22, _tf_mat_23}, {_tf_mat_31, _tf_mat_32, _tf_mat_33}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(4)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13}, {_tf_mat_21, _tf_mat_22, _tf_mat_23}, {_tf_mat_31, _tf_mat_32, _tf_mat_33}, {_tf_mat_41, _tf_mat_42, _tf_mat_43}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(5)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13}, {_tf_mat_21, _tf_mat_22, _tf_mat_23}, {_tf_mat_31, _tf_mat_32, _tf_mat_33}, {_tf_mat_41, _tf_mat_42, _tf_mat_43}
                            , {_tf_mat_51, _tf_mat_52, _tf_mat_53}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(6)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13}, {_tf_mat_21, _tf_mat_22, _tf_mat_23}, {_tf_mat_31, _tf_mat_32, _tf_mat_33}, {_tf_mat_41, _tf_mat_42, _tf_mat_43}
                            , {_tf_mat_51, _tf_mat_52, _tf_mat_53}, {_tf_mat_61, _tf_mat_62, _tf_mat_63}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5, _tf_warunek6};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                }

            } else if (iloscMaterialu.equals(4)) {
                if (illoscWarunkow.equals(1)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13, _tf_mat_14}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3, _tf_zysk4};
                    double[] b = new double[]{_tf_warunek1};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(2)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13, _tf_mat_14}, {_tf_mat_21, _tf_mat_22, _tf_mat_23, _tf_mat_24}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3, _tf_zysk4};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(3)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13, _tf_mat_14}, {_tf_mat_21, _tf_mat_22, _tf_mat_23, _tf_mat_24}, {_tf_mat_31, _tf_mat_32, _tf_mat_33, _tf_mat_34}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3, _tf_zysk4};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(4)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13, _tf_mat_14}, {_tf_mat_21, _tf_mat_22, _tf_mat_23, _tf_mat_24}, {_tf_mat_31, _tf_mat_32, _tf_mat_33, _tf_mat_34}, {_tf_mat_41, _tf_mat_42, _tf_mat_43, _tf_mat_44}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3, _tf_zysk4};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(5)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13, _tf_mat_14}, {_tf_mat_21, _tf_mat_22, _tf_mat_23, _tf_mat_24}, {_tf_mat_31, _tf_mat_32, _tf_mat_33, _tf_mat_34}, {_tf_mat_41, _tf_mat_42, _tf_mat_43, _tf_mat_44}
                            , {_tf_mat_51, _tf_mat_52, _tf_mat_53, _tf_mat_54}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3, _tf_zysk4};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                } else if (illoscWarunkow.equals(6)) {
                    double[][] A = {{_tf_mat_11, _tf_mat_12, _tf_mat_13, _tf_mat_14}, {_tf_mat_21, _tf_mat_22, _tf_mat_23, _tf_mat_24}, {_tf_mat_31, _tf_mat_32, _tf_mat_33, _tf_mat_34}, {_tf_mat_41, _tf_mat_42, _tf_mat_43, _tf_mat_44}
                            , {_tf_mat_51, _tf_mat_52, _tf_mat_53, _tf_mat_54}, {_tf_mat_61, _tf_mat_62, _tf_mat_63, _tf_mat_64}};
                    double[] c = {_tf_zysk1, _tf_zysk2, _tf_zysk3, _tf_zysk4};
                    double[] b = new double[]{_tf_warunek1, _tf_warunek2, _tf_warunek3, _tf_warunek4, _tf_warunek5, _tf_warunek6};
                    Solver.solveModel(n, m, c, A, b, tf_komCel, tf_ilSztuk1, tf_ilSztuk2, tf_ilSztuk3, tf_ilSztuk4);
                }
            }
        });

        cb_ilWarunkow.setOnAction(event -> {
            ustawIlosci();
            ustawPola();
        });

        cb_IlMat.setOnAction(event -> {
            ustawIlosci();
            ustawPola();
        });

    }


    private void ustawIlosci() {
        illoscWarunkow = Integer.parseInt(cb_ilWarunkow.getSelectionModel().getSelectedItem().toString());
        iloscMaterialu = Integer.parseInt(cb_IlMat.getSelectionModel().getSelectedItem().toString());
    }


    private void ustawPola() {
        if (illoscWarunkow.equals(1) && iloscMaterialu.equals(1)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(true);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(true);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(true);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(true);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        } else if (illoscWarunkow.equals(1) && iloscMaterialu.equals(2)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(true);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(true);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        } else if (illoscWarunkow.equals(1) && iloscMaterialu.equals(3)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(true);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(true);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
        } else if (illoscWarunkow.equals(1) && iloscMaterialu.equals(4)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(false);
            tf_mat_21.setDisable(true);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(true);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
        }
        if (illoscWarunkow.equals(2) && iloscMaterialu.equals(1)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(true);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(true);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(2) && iloscMaterialu.equals(2)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(2) && iloscMaterialu.equals(3)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(2) && iloscMaterialu.equals(4)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(false);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(false);
            tf_mat_31.setDisable(true);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(true);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
        }
        if (illoscWarunkow.equals(3) && iloscMaterialu.equals(1)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(true);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(true);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(3) && iloscMaterialu.equals(2)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(3) && iloscMaterialu.equals(3)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(3) && iloscMaterialu.equals(4)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(false);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(false);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(false);
            tf_mat_41.setDisable(true);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(true);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
        }
        if (illoscWarunkow.equals(4) && iloscMaterialu.equals(1)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(true);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(true);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(4) && iloscMaterialu.equals(2)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(4) && iloscMaterialu.equals(3)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(false);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(4) && iloscMaterialu.equals(4)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(false);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(false);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(false);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(false);
            tf_mat_44.setDisable(false);
            tf_mat_51.setDisable(true);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(true);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
        }
        if (illoscWarunkow.equals(5) && iloscMaterialu.equals(1)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(true);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(true);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(5) && iloscMaterialu.equals(2)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(false);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(5) && iloscMaterialu.equals(3)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(false);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(false);
            tf_mat_53.setDisable(false);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(5) && iloscMaterialu.equals(4)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(false);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(false);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(false);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(false);
            tf_mat_44.setDisable(false);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(false);
            tf_mat_53.setDisable(false);
            tf_mat_54.setDisable(false);
            tf_mat_61.setDisable(true);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
        }
        if (illoscWarunkow.equals(6) && iloscMaterialu.equals(1)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(true);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(true);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(true);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(true);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(true);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(false);
            tf_mat_62.setDisable(true);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(true);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(true);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(6) && iloscMaterialu.equals(2)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(true);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(true);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(true);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(true);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(false);
            tf_mat_53.setDisable(true);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(false);
            tf_mat_62.setDisable(false);
            tf_mat_63.setDisable(true);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(true);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(true);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(6) && iloscMaterialu.equals(3)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(true);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(true);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(true);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(false);
            tf_mat_44.setDisable(true);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(false);
            tf_mat_53.setDisable(false);
            tf_mat_54.setDisable(true);
            tf_mat_61.setDisable(false);
            tf_mat_62.setDisable(false);
            tf_mat_63.setDisable(false);
            tf_mat_64.setDisable(true);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(true);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(true);
        }
        if (illoscWarunkow.equals(6) && iloscMaterialu.equals(4)) {
            tf_mat_11.setDisable(false);
            tf_mat_12.setDisable(false);
            tf_mat_13.setDisable(false);
            tf_mat_14.setDisable(false);
            tf_mat_21.setDisable(false);
            tf_mat_22.setDisable(false);
            tf_mat_23.setDisable(false);
            tf_mat_24.setDisable(false);
            tf_mat_31.setDisable(false);
            tf_mat_32.setDisable(false);
            tf_mat_33.setDisable(false);
            tf_mat_34.setDisable(false);
            tf_mat_41.setDisable(false);
            tf_mat_42.setDisable(false);
            tf_mat_43.setDisable(false);
            tf_mat_44.setDisable(false);
            tf_mat_51.setDisable(false);
            tf_mat_52.setDisable(false);
            tf_mat_53.setDisable(false);
            tf_mat_54.setDisable(false);
            tf_mat_61.setDisable(false);
            tf_mat_62.setDisable(false);
            tf_mat_63.setDisable(false);
            tf_mat_64.setDisable(false);
            tf_zysk1.setDisable(false);
            tf_zysk2.setDisable(false);
            tf_zysk3.setDisable(false);
            tf_zysk4.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
            tf_warunek1.setDisable(false);
            tf_warunek2.setDisable(false);
            tf_warunek3.setDisable(false);
            tf_warunek4.setDisable(false);
            tf_warunek5.setDisable(false);
            tf_warunek6.setDisable(false);
            tf_ilSztuk1.setDisable(false);
            tf_ilSztuk2.setDisable(false);
            tf_ilSztuk3.setDisable(false);
            tf_ilSztuk4.setDisable(false);
        }
    }

}